### ISSUE TITLE
Luna Performance

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#251]
### Summary
Currently, Luna's performance is subpar, meaning that interpreted code is not as efficient as it could be. Not only does this lead to longer-than-desirable iteration times on interpreted code, but means that we are at a competitive disadvantage to other languages like Python.

### Value
Improving the performance of Luna brings obvious benefits to users, allowing them both more performant code and to spend less time waiting on the interpreter in general. Furthermore, increasing interpreted performance to _at least_ the level of Python means that Luna, with its cutting-edge visualisation capabilities, will be back at a competitive advantage with other languages commonly used for data processing. 

### Specification
This Epic aims to give Luna's runtime the following properties. 

- [ ] Startup time comparable to Python (preferably faster).
- [ ] Execution performance faster than that of Python (as measured by the execution of similar code). 
- [ ] Measurable increases to evaluation speed.
- [ ] Caching and graph performance enhancements if possible. 

### Acceptance Criteria & Test Cases
For the first attempt at this Epic, acceptance of features will be determined by the following criteria:

- [ ] Measured (real) increases in execution speed on a set of benchmarks.
- [ ] Interpreter startup speed decreased by _at least_ 25%. 
- [ ] Execution time comparable to Python.
