### ISSUE TITLE
Luna Runtime

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#314]
### Summary
Luna's current interpreter was never meant as more than a stopgap measure to allow execution of Luna code until a more comprehensive one could be developed. This epic exists to track the tasks required for designing and implementing the new Luna runtime. 

### Value
This new runtime will bring dual benefits to Luna and its ecosystem:

1. **Performance:** The new runtime will be designed from scratch with performance in mind, bringing significant performance increases to our users and the ecosystem as a whole. This performance will both be more _predictable_, but also just plain faster than the current runtime, making Luna far more competitive with other languages in the same space. 
2. **Future-Proofing:** The new runtime will also be designed to accommodate the sophisticated features that we want to build into Luna in the future (e.g. result caching, result freezing, tiered compilation, performance and memory tracing and manual optimisation). 

Together, this forms a broad motivation for the need to redesign and develop the runtime from scratch, rather than improving the existing one. 

### Specification

- Execution performance should be in line with LuaJIT or faster.
- Runtime start performance should be no slower than LuaJIT. 
- The new runtime supports all the advanced features required of it, as detailed in the [Runtime Design](https://github.com/luna/luna-rfcs/blob/runtime-design/text/0000-runtime-design.md) RFC. 

### Acceptance Criteria & Test Cases

- [ ] Performance of executed code is as good as or better than LuaJIT when executing semantically equivalent code.
- [ ] The runtime starts as quickly as that of LuaJIT (in the same order of magnitude). 
- [ ] The runtime implements all features and functionality described in the aforementioned [RFC](https://github.com/luna/luna-rfcs/blob/runtime-design/text/0000-runtime-design.md).
