### ISSUE TITLE
Java FFI

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#625]
### Summary
Where many programming languages provide the ability to perform FFI with C, running on GraalVM gives Enso access to a whole wealth of libraries implemented in Java and other JVM languages. To that end, we want to enable a higher-level FFI with Java, allowing Enso users to back their programs with a comprehensive library ecosystem as needed. 

### Value
We will have proved the concept of foreign interop with Java, as well as provided useful backing functionality for working with Java libraries in implementing the standard library. 

### Specification

- [x] Perform research into reflection-based Java interop (#683).
- [x] Investigate the performance of reflection-based Java interop (#684).
- [x] Design the surface-language syntax for Java FFI (#685).
- [x] Implement the Java FFI (#686).

### Acceptance Criteria & Test Cases

- The above specification has been completed, and all tasks have met their acceptance criteria.
