### ISSUE TITLE
Runtime Caching

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#632]
### Summary
One of the most important features for Enso is the runtime cache. This refers to the ability to cache intermediate results in introspected scopes in order to improve interactivity for our users. 

The runtime cache is a sophisticated piece of machinery, combining the dataflow analysis from the compiler, an externally orchestrated cache, and the sophisticated instrospection machinery provided by truffle to allow us to reuse cached values at runtime.

### Value
Value caching will be enabled in the runtime, providing a much more interactive experience to users while working on large amounts of data. 

### Specification
Complete the following tasks:

- [x] Update the PoC of caching injection to work with external identifiers (#676).
- [x] Add support for returning the transitive closure of _external_ identifiers to the dataflow analysis pass (#677).
- [x] Fix up the execution context (#732).
- [x] Determine the set of changed internal identifiers using the textual diff (#678).
- [x] Design and implement the runtime cache (#679, luna/luna#627).
- [x] Plumb together the components to enable runtime caching (#681).

### Acceptance Criteria & Test Cases

- All of the above listed issues have been completed and have met their own acceptance criteria.
