### ISSUE TITLE
Migrate the REPL and Debugger to a Server-Based Solution

### ISSUE THREAD

**Issue by kustosz** [luna/luna#650]
### Summary
We are currently using unhygienic operations (i.e. [lookupClass](https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/Instrument.html#lookup-java.lang.Class-)) for interacting with the Enso Debugger from the polyglot context. This blocks us from conforming to the structure expected by Truffle and resorting to hacks to make the whole application work (i.e. the program has to be run with classpath separation disabled).

This should be changed, using a server-based solution instead.

### Value
1. We can treat Enso like any other Truffle language.
2. We can invest more time into REPL development, without the fear of the additional work going to waste.

### Specification
As the following steps are completed, each should be able to land on `master` without breaking anything.

- [x] Design and implement a binary protocol for the debugger (#789). 
- [x] Handle messages in the instrument using a server (#790). 
- [x] Migrate the repl to use this new server (#791).
- [x] Fix the CI build and distribution to conform to the spec (#792). 

### Acceptance Criteria & Test Cases

- All functionality is tested and documented.
- The code conforms to the code styles described in this repository.
- The functionality conforms to the above specification.
