### ISSUE TITLE
Project Manager Service

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna#685]
### Summary
Given that the language server instance used by the IDE corresponds only to an individual project, we also need to provide the IDE with a way to manage multiple projects. This will take the form of a separate service called the project manager that is responsible for providing project-related services, but also spooling up and shutting down the language server on a per-project basis.

### Value
Users will have the ability to work with multiple projects.

### Specification

- [x] Create the scaffolding for the language server supervisor process (#524).
- [x] Implement opening and closing of projects (#525, luna/luna#682).
- [x] Implement the supervisor functionality (#337).
- [x] Project creation and deletion (#527).
- [x] Recent projects listing (#528).

### Acceptance Criteria & Test Cases

- The above specification has been completed.
- Each portion of the specification is accompanied by rigorous tests.
